version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80 # Fuerza a escuchar en todas las IPs
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=library;User=root;Password=password;AllowPublicKeyRetrieval=true;SslMode=None;CharSet=utf8mb4
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_HOST=%
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Infrastructure/Data/Init:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
      --init-connect='SET collation_connection = utf8mb4_unicode_ci'
      --bind-address=0.0.0.0

volumes:
  mysql_data:
